version: '3'
services:

  database:
      image: postgres:11.4
      volumes:
          - ./db_data/pgdata:/var/lib/postgresql/data/
      environment:
          POSTGRES_USER: django
          POSTGRES_HOST_AUTH_METHOD: "trust"
      ports:
        - "5432"

  api:
      image: urandu/face-detection-api:a0fbc99c1862c39997e43252b1bac21ef6cfad00
      command: ./bin/web_entrypoint.sh
      volumes:
          - ./:/django
      ports:
          - "8900:8000"
      env_file: &envfile
        - env.env
      depends_on:
        - broker
        - redis
        - database

  broker:
      image: rabbitmq:3.6.16-management-alpine
      env_file: *envfile
      ports:
        - 5672
        - 15672
        - 5671

  redis:
      image: 'bitnami/redis:latest'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      ports:
        - "6379"

  worker:
      image: urandu/face-detection-api:a0fbc99c1862c39997e43252b1bac21ef6cfad00
      command: ./bin/worker_entrypoint.sh
      volumes:
          - ./:/django
      links:
          - database
      env_file: *envfile
      depends_on:
        - broker
        - redis
        - database

  minio:
        image: "minio/minio"
        command: server /data
        env_file: *envfile
        ports:
            - "9000:9000"
        volumes:
            - ./storage/minio:/data
