# Generated by Django 2.2.5 on 2019-09-24 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190924_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='request_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
