name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: facedetect_api
jobs:
  push_to_registry:
    name: Push Docker image to urandu registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.URANDU_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.URANDU_DOCKER_REGISTRY_PASSWORD }}
          registry: urandu-local-docker-registry.loca.lt/facedetect_api
          repository: facedetect_api
          tag_with_ref: true
